services:

  postgres:
    image: postgres:17
    container_name: susuerte-db

    environment:
      POSTGRES_DB: susuerte
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5436:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  php:
    build: .

    container_name: susuerte-php
    ports:
      - "8000:8000"

    working_dir: /app

    volumes:
      - .:/app

    stdin_open: true
    tty: true

volumes:
  postgres_data:
